name: build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan

      - name: Generate project files
        run: python automation/generate_project_files.py

      - name: Build Debug
        run: python automation/build_debug.py

      - name: Build Release
        run: python automation/build_release.py

      - name: Check formatting
        run: python automation/format_files.py --check